name: Docker push 

on: [push]

jobs:
  build:
  docker:
    runs on: ubuntu-latest

    steps:

    - name: set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: build and push 
      uses: docker/setup-buildx-action@v3

      name: build and push container images 
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: user/app:latest